'use client';

import React, { useEffect, useState, useMemo } from 'react';
import { useSession } from 'next-auth/react';
import {
  Search,
  Download,
  PlusCircle,
  CheckCircle2,
  SlidersHorizontal,
  Music2,
} from 'lucide-react';
import { getTopTracks, getMe, createPlaylistWithTracks } from '@/lib/spotify';
import type { SpotifyTrack, TimeRange } from '@/types/spotify';
import PageHeader from '@/components/PageHeader';
import TrackRow from '@/components/TrackRow';
import TimeRangeTabs from '@/components/TimeRangeTabs';
import { TrackListSkeleton } from '@/components/Skeleton';
import { ErrorState, EmptyState } from '@/components/StateViews';

type SortOption = 'rank' | 'name' | 'artist' | 'duration' | 'popularity';

export default function TopTracksPage() {
  const { data: session } = useSession();
  const token = (session as any)?.accessToken as string | undefined;

  const [range, setRange] = useState<TimeRange>('medium_term');
  const [tracks, setTracks] = useState<SpotifyTrack[] | null>(null);
  const [error, setError] = useState<string | null>(null);

  const [searchQuery, setSearchQuery] = useState('');
  const [sortBy, setSortBy] = useState<SortOption>('rank');

  const [savingPlaylist, setSavingPlaylist] = useState(false);
  const [savedPlaylistUrl, setSavedPlaylistUrl] = useState<string | null>(null);

  useEffect(() => {
    if (!token) return;
    setTracks(null);
    setError(null);
    setSavedPlaylistUrl(null);
    getTopTracks(token, range, 50)
      .then((res) => setTracks(res.items))
      .catch((e) => setError(e.message));
  }, [token, range]);

  // Filter & sort tracks
  const filteredTracks = useMemo(() => {
    if (!tracks) return [];
    let result = [...tracks];

    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      result = result.filter(
        (t) =>
          t.name.toLowerCase().includes(q) ||
          t.artists.some((a) => a.name.toLowerCase().includes(q)) ||
          t.album.name.toLowerCase().includes(q)
      );
    }

    result.sort((a, b) => {
      if (sortBy === 'name') return a.name.localeCompare(b.name);
      if (sortBy === 'artist') {
        const artistA = a.artists[0]?.name ?? '';
        const artistB = b.artists[0]?.name ?? '';
        return artistA.localeCompare(artistB);
      }
      if (sortBy === 'duration') return b.duration_ms - a.duration_ms;
      if (sortBy === 'popularity') return (b.popularity ?? 0) - (a.popularity ?? 0);
      return (tracks.indexOf(a) ?? 0) - (tracks.indexOf(b) ?? 0);
    });

    return result;
  }, [tracks, searchQuery, sortBy]);

  // Export tracks to CSV
  const handleExportCSV = () => {
    if (!filteredTracks.length) return;
    const rangeLabel =
      range === 'short_term' ? '4weeks' : range === 'medium_term' ? '6months' : 'alltime';
    const headers = ['Rank', 'Title', 'Artists', 'Album', 'Duration_Sec', 'Popularity', 'Spotify_URL'];
    const rows = filteredTracks.map((t, i) => [
      i + 1,
      `"${t.name.replace(/"/g, '""')}"`,
      `"${t.artists.map((a) => a.name).join(', ').replace(/"/g, '""')}"`,
      `"${t.album.name.replace(/"/g, '""')}"`,
      Math.round(t.duration_ms / 1000),
      t.popularity ?? '',
      t.external_urls.spotify,
    ]);

    const csvContent =
      'data:text/csv;charset=utf-8,' +
      [headers.join(','), ...rows.map((e) => e.join(','))].join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `sonalyze-top-tracks-${rangeLabel}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // One-click save to Spotify playlist
  const handleCreatePlaylist = async () => {
    if (!token || !filteredTracks.length) return;
    setSavingPlaylist(true);
    setError(null);
    try {
      const me = await getMe(token);
      const rangeName =
        range === 'short_term'
          ? 'Last 4 Weeks'
          : range === 'medium_term'
          ? 'Last 6 Months'
          : 'All Time';
      const name = `My Top Tracks (${rangeName}) — Sonalyze`;
      const description = `Top tracks generated by Sonalyze on ${new Date().toLocaleDateString()}.`;
      const uris = filteredTracks.map((t) => `spotify:track:${t.id}`);

      const playlist = await createPlaylistWithTracks(token, me.id, name, description, uris, false);
      setSavedPlaylistUrl(playlist.external_urls.spotify);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setSavingPlaylist(false);
    }
  };

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Your Library"
        title="Top tracks"
        description="Your most-played songs with audio preview streaming, detailed audio DNA radars, and CSV export."
        action={<TimeRangeTabs value={range} onChange={setRange} />}
      />

      {error && <ErrorState message="Couldn't load your top tracks." hint={error} />}

      {/* Control Bar: Search, Sort, Export, Save Playlist */}
      {tracks && tracks.length > 0 && (
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between rounded-2xl border border-white/8 bg-panel/30 p-3 backdrop-blur">
          {/* Search Input */}
          <div className="relative flex-1 max-w-sm">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-subtle" />
            <input
              type="text"
              placeholder="Search by title, artist, or album…"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full rounded-xl border border-white/8 bg-elevated/80 pl-9 pr-3 py-1.5 text-xs text-cream placeholder-subtle outline-none focus:border-accent/40"
            />
          </div>

          {/* Sort & Actions */}
          <div className="flex flex-wrap items-center gap-2">
            <div className="flex items-center gap-1.5 rounded-xl border border-white/8 bg-elevated/80 px-2.5 py-1 text-xs text-muted">
              <SlidersHorizontal className="h-3.5 w-3.5 text-subtle" />
              <select
                value={sortBy}
                onChange={(e) => setSortBy(e.target.value as SortOption)}
                aria-label="Sort tracks by"
                className="bg-transparent text-xs text-cream outline-none cursor-pointer"
              >
                <option value="rank" className="bg-panel text-cream">Sort: Rank</option>
                <option value="name" className="bg-panel text-cream">Sort: Title</option>
                <option value="artist" className="bg-panel text-cream">Sort: Artist</option>
                <option value="popularity" className="bg-panel text-cream">Sort: Popularity</option>
                <option value="duration" className="bg-panel text-cream">Sort: Duration</option>
              </select>
            </div>

            <button
              onClick={handleExportCSV}
              className="flex items-center gap-1.5 rounded-xl border border-white/8 bg-elevated/80 px-3 py-1.5 text-xs font-medium text-muted hover:text-cream hover:bg-elevated transition-colors"
              title="Download tracks as CSV spreadsheet"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Export CSV</span>
            </button>

            {savedPlaylistUrl ? (
              <a
                href={savedPlaylistUrl}
                target="_blank"
                rel="noreferrer"
                className="flex items-center gap-1.5 rounded-xl bg-accent/20 px-3 py-1.5 text-xs font-semibold text-accent hover:bg-accent/30 transition-colors"
              >
                <CheckCircle2 className="h-3.5 w-3.5" />
                <span>Open Playlist</span>
              </a>
            ) : (
              <button
                onClick={handleCreatePlaylist}
                disabled={savingPlaylist}
                className="flex items-center gap-1.5 rounded-xl bg-accent px-3 py-1.5 text-xs font-semibold text-black transition-transform hover:scale-105 active:scale-95 disabled:opacity-50"
              >
                <PlusCircle className="h-3.5 w-3.5" />
                <span>{savingPlaylist ? 'Saving…' : 'Save Playlist'}</span>
              </button>
            )}
          </div>
        </div>
      )}

      {/* Skeletons & Content */}
      {!error && !tracks && <TrackListSkeleton count={10} />}

      {tracks && tracks.length === 0 && (
        <EmptyState
          title="No top tracks yet"
          body="Spotify needs a bit more listening history before it can rank your tracks for this period."
        />
      )}

      {tracks && tracks.length > 0 && filteredTracks.length === 0 && (
        <EmptyState
          title="No matching tracks"
          body={`No tracks match "${searchQuery}". Try a different keyword.`}
        />
      )}

      {filteredTracks.length > 0 && (
        <div className="rounded-2xl border border-white/8 bg-panel/40 p-2 shadow-inner">
          {filteredTracks.map((t, i) => (
            <TrackRow
              key={t.id}
              track={t}
              rank={sortBy === 'rank' ? (tracks ? tracks.indexOf(t) + 1 : i + 1) : undefined}
              meta={
                sortBy === 'popularity'
                  ? `Popularity ${t.popularity ?? 0}/100`
                  : undefined
              }
            />
          ))}
        </div>
      )}
    </div>
  );
}
