'use client';

import { useEffect, useState } from 'react';
import { useSession } from 'next-auth/react';
import { Wand2, CheckCircle2, ExternalLink, RefreshCw } from 'lucide-react';
import {
  getUserPlaylists,
  getPlaylistTracks,
  getRecommendations,
  createPlaylist,
  addTracksToPlaylist,
  getMe,
  SpotifyApiError,
} from '@/lib/spotify';
import type { SpotifyPlaylist, SpotifyTrack } from '@/types/spotify';
import PageHeader from '@/components/PageHeader';
import { LoadingState, ErrorState } from '@/components/StateViews';
import TrackRow from '@/components/TrackRow';

type Stage = 'pick' | 'tuning' | 'results' | 'saved';

export default function DiscoverPage() {
  const { data: session } = useSession();
  const token = (session as any)?.accessToken as string | undefined;

  const [stage, setStage] = useState<Stage>('pick');
  const [playlists, setPlaylists] = useState<SpotifyPlaylist[] | null>(null);
  const [selectedPlaylist, setSelectedPlaylist] = useState<string>('');
  const [error, setError] = useState<string | null>(null);

  const [energy, setEnergy] = useState(0.6);
  const [valence, setValence] = useState(0.6);
  const [danceability, setDanceability] = useState(0.6);

  const [loadingRecs, setLoadingRecs] = useState(false);
  const [recommendations, setRecommendations] = useState<SpotifyTrack[]>([]);
  const [selected, setSelected] = useState<Set<string>>(new Set());

  const [playlistName, setPlaylistName] = useState('');
  const [playlistDesc, setPlaylistDesc] = useState('');
  const [saving, setSaving] = useState(false);
  const [savedUrl, setSavedUrl] = useState<string | null>(null);

  useEffect(() => {
    if (!token) return;
    getUserPlaylists(token, 50)
      .then((res) => setPlaylists(res.items.filter(Boolean)))
      .catch((e) => setError(e.message));
  }, [token]);

  async function generate() {
    if (!token || !selectedPlaylist) return;
    setLoadingRecs(true);
    setError(null);
    try {
      const { items } = await getPlaylistTracks(token, selectedPlaylist, 30);
      const trackIds = items.map((i) => i.track?.id).filter(Boolean) as string[];
      const seedTracks = [...trackIds].sort(() => Math.random() - 0.5).slice(0, 5);

      if (seedTracks.length === 0) {
        setError('That playlist has no playable tracks to use as a seed.');
        setLoadingRecs(false);
        return;
      }

      const res = await getRecommendations(token, {
        seedTracks,
        targetEnergy: energy,
        targetValence: valence,
        targetDanceability: danceability,
        limit: 20,
      });
      setRecommendations(res.tracks);
      setSelected(new Set(res.tracks.map((t) => t.id)));

      const seedPlaylist = playlists?.find((p) => p.id === selectedPlaylist);
      setPlaylistName(`${seedPlaylist?.name ?? 'My mix'} — Recommended`);
      setPlaylistDesc(`Generated by Sonalyze from "${seedPlaylist?.name ?? 'a playlist'}".`);

      setStage('results');
    } catch (e: any) {
      if (e instanceof SpotifyApiError && e.status === 403) {
        setError(
          "Spotify's recommendation engine isn't available for this app's access level. This feature needs an app with extended API access."
        );
      } else {
        setError(e.message);
      }
    } finally {
      setLoadingRecs(false);
    }
  }

  function toggleTrack(id: string) {
    setSelected((prev) => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  }

  async function save() {
    if (!token) return;
    setSaving(true);
    setError(null);
    try {
      const me = await getMe(token);
      const chosen = recommendations.filter((t) => selected.has(t.id));
      const playlist = await createPlaylist(
        token,
        me.id,
        playlistName || 'My generated mix',
        playlistDesc,
        false
      );
      await addTracksToPlaylist(
        token,
        playlist.id,
        chosen.map((t) => `spotify:track:${t.id}`)
      );
      setSavedUrl(playlist.external_urls.spotify);
      setStage('saved');
    } catch (e: any) {
      setError(e.message);
    } finally {
      setSaving(false);
    }
  }

  function reset() {
    setStage('pick');
    setSelectedPlaylist('');
    setRecommendations([]);
    setSelected(new Set());
    setSavedUrl(null);
    setError(null);
  }

  return (
    <div>
      <PageHeader
        eyebrow="Create"
        title="Playlist generator"
        description="Pick one of your playlists as a starting point, tune the mood, and Sonalyze will suggest new tracks you can save straight to Spotify."
      />

      {error && <ErrorState message="Something went wrong." hint={error} />}

      {stage === 'pick' && (
        <div className="max-w-xl">
          {!playlists && !error && <LoadingState label="Loading your playlists" />}
          {playlists && (
            <div className="space-y-6 rounded-2xl border border-white/8 bg-panel/40 p-6">
              <div>
                <label className="mb-2 block text-sm font-medium text-cream">
                  Choose a seed playlist
                </label>
                <select
                  value={selectedPlaylist}
                  onChange={(e) => setSelectedPlaylist(e.target.value)}
                  className="w-full rounded-lg border border-white/10 bg-elevated px-4 py-2.5 text-sm text-cream focus:border-accent focus:outline-none"
                >
                  <option value="">Select a playlist…</option>
                  {playlists.map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.name} ({p.tracks.total} tracks)
                    </option>
                  ))}
                </select>
              </div>

              <button
                disabled={!selectedPlaylist}
                onClick={() => setStage('tuning')}
                className="inline-flex items-center gap-2 rounded-full bg-accent px-5 py-2.5 text-sm font-semibold text-black transition-transform hover:scale-[1.03] disabled:cursor-not-allowed disabled:opacity-40"
              >
                Next: tune the mood
              </button>
            </div>
          )}
        </div>
      )}

      {stage === 'tuning' && (
        <div className="max-w-xl space-y-6 rounded-2xl border border-white/8 bg-panel/40 p-6">
          <Slider label="Energy" value={energy} onChange={setEnergy} lowLabel="Mellow" highLabel="Intense" />
          <Slider label="Mood" value={valence} onChange={setValence} lowLabel="Moody" highLabel="Upbeat" />
          <Slider
            label="Danceability"
            value={danceability}
            onChange={setDanceability}
            lowLabel="Freeform"
            highLabel="Groove-heavy"
          />

          <div className="flex gap-3">
            <button
              onClick={() => setStage('pick')}
              className="rounded-full border border-white/10 px-5 py-2.5 text-sm font-medium text-muted hover:text-cream"
            >
              Back
            </button>
            <button
              onClick={generate}
              disabled={loadingRecs}
              className="inline-flex items-center gap-2 rounded-full bg-accent px-5 py-2.5 text-sm font-semibold text-black transition-transform hover:scale-[1.03] disabled:opacity-60"
            >
              <Wand2 className="h-4 w-4" />
              {loadingRecs ? 'Generating…' : 'Generate recommendations'}
            </button>
          </div>
        </div>
      )}

      {stage === 'results' && (
        <div className="space-y-6">
          <div className="rounded-2xl border border-white/8 bg-panel/40 p-2">
            {recommendations.map((t) => (
              <label
                key={t.id}
                className="flex cursor-pointer items-center gap-3 rounded-xl px-3 transition-colors hover:bg-elevated/40"
              >
                <input
                  type="checkbox"
                  checked={selected.has(t.id)}
                  onChange={() => toggleTrack(t.id)}
                  className="h-4 w-4 shrink-0 accent-accentDeep"
                />
                <div className="flex-1">
                  <TrackRow track={t} />
                </div>
              </label>
            ))}
          </div>

          <div className="max-w-xl space-y-4 rounded-2xl border border-white/8 bg-panel/40 p-6">
            <div>
              <label className="mb-2 block text-sm font-medium text-cream">Playlist name</label>
              <input
                value={playlistName}
                onChange={(e) => setPlaylistName(e.target.value)}
                className="w-full rounded-lg border border-white/10 bg-elevated px-4 py-2.5 text-sm text-cream focus:border-accent focus:outline-none"
              />
            </div>
            <div>
              <label className="mb-2 block text-sm font-medium text-cream">Description</label>
              <input
                value={playlistDesc}
                onChange={(e) => setPlaylistDesc(e.target.value)}
                className="w-full rounded-lg border border-white/10 bg-elevated px-4 py-2.5 text-sm text-cream focus:border-accent focus:outline-none"
              />
            </div>
            <div className="flex gap-3">
              <button
                onClick={() => setStage('tuning')}
                className="inline-flex items-center gap-2 rounded-full border border-white/10 px-5 py-2.5 text-sm font-medium text-muted hover:text-cream"
              >
                <RefreshCw className="h-4 w-4" /> Adjust mood
              </button>
              <button
                onClick={save}
                disabled={saving || selected.size === 0}
                className="inline-flex items-center gap-2 rounded-full bg-accent px-5 py-2.5 text-sm font-semibold text-black transition-transform hover:scale-[1.03] disabled:opacity-60"
              >
                {saving ? 'Saving…' : `Save ${selected.size} tracks to Spotify`}
              </button>
            </div>
          </div>
        </div>
      )}

      {stage === 'saved' && savedUrl && (
        <div className="flex max-w-xl flex-col items-center gap-4 rounded-2xl border border-accent/30 bg-accent/5 p-10 text-center">
          <CheckCircle2 className="h-10 w-10 text-accent" />
          <h2 className="font-display text-xl font-semibold tracking-tight">Playlist saved</h2>
          <p className="text-sm text-muted">
            "{playlistName}" is now in your Spotify library.
          </p>
          <div className="flex gap-3">
            <a
              href={savedUrl}
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center gap-2 rounded-full bg-accent px-5 py-2.5 text-sm font-semibold text-black transition-transform hover:scale-[1.03]"
            >
              Open in Spotify <ExternalLink className="h-4 w-4" />
            </a>
            <button
              onClick={reset}
              className="rounded-full border border-white/10 px-5 py-2.5 text-sm font-medium text-muted hover:text-cream"
            >
              Make another
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

function Slider({
  label,
  value,
  onChange,
  lowLabel,
  highLabel,
}: {
  label: string;
  value: number;
  onChange: (v: number) => void;
  lowLabel: string;
  highLabel: string;
}) {
  return (
    <div>
      <div className="mb-2 flex items-baseline justify-between">
        <span className="text-sm font-medium text-cream">{label}</span>
        <span className="text-xs text-subtle">{Math.round(value * 100)}%</span>
      </div>
      <input
        type="range"
        min={0}
        max={1}
        step={0.05}
        value={value}
        onChange={(e) => onChange(parseFloat(e.target.value))}
        className="w-full accent-accentDeep"
      />
      <div className="mt-1 flex justify-between text-[11px] text-subtle">
        <span>{lowLabel}</span>
        <span>{highLabel}</span>
      </div>
    </div>
  );
}
