domains:
- domain: sonalyze.daywalker.dev
  type: PRIMARY
  zone: daywalker.dev
ingress:
  rules:
  - component:
      name: web
    match:
      path:
        prefix: /
name: sonalyze
region: nyc
services:
- dockerfile_path: Dockerfile
  envs:
  - key: SPOTIFY_CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:evbaYO5OdJpyNUtvubJpDwoJAU8BHNGG:97wAqqWF75lsg4XQwx5hc3Yr4Ko4xJTgP1ihOnZk1DRztZ11QXXFlhvJkEmjS8Gs]
  - key: SPOTIFY_CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:JHg2kku/YgRDbXYMtjB/x5NNGjdJZs82:syS04cRkl8lW3B31IAFcrO1kUno2hMP9vgHxjjIEpUINJjXs/orw6u0k7SvXVDmb]
  - key: NEXTAUTH_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:msfEYA6TL7JGfGjRm8pUii7dnU6dhsTA:G6bl4Pw2n1iZscCrh1rrEV0y5viySUv7eAckjdYnskgdFreJMUn4fGFstV35+ch7UdHiyc8Ot9aCb4JqLT32stHH9RHRqSShdsaCmgXUG5Q=]
  - key: NEXTAUTH_URL
    scope: RUN_AND_BUILD_TIME
    value: ${APP_URL}
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: DAYWALKER_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:MmqHgR18QKIuDreRzN9oY01E3TlSOsyA:1y6b9o7S0CCE9MH9FZEZr+6EBt3G2XfpCmkyTF0vrOl7qhU2IHIfiM39j3zKQtvIXSwCKqMqs9QsCEdDni+DyvQU3wKaai7Ey2sT5+dXudgO1/xFKVfObIU=]
  github:
    branch: main
    deploy_on_push: true
    repo: Shelbyb/sonalyze
  health_check:
    failure_threshold: 3
    http_path: /api/health
    initial_delay_seconds: 10
    period_seconds: 15
    timeout_seconds: 5
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: web
  source_dir: /
